# Generated by Django 4.1.1 on 2022-09-24 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('user_type', models.CharField(choices=[('Частное', 'Private'), ('Юр. лицо', 'Legal Entity')], default='Частное', max_length=50)),
                ('user_anketa_status', models.CharField(choices=[("('SOLVED', 'Решено')", 'Solved'), ("('ACTIVE', 'Активно')", 'Active'), ("('IN_PROCESS', 'В процессе')", 'In Process'), ("('REJECTED', 'Отклонено')", 'Rejected')], default="('ACTIVE', 'Активно')", max_length=50)),
                ('user_anketa_data', models.CharField(default=None, max_length=4096)),
                ('settings', models.CharField(blank=True, default=None, max_length=50)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'UserAccount',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='UserAnketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
