# Generated by Django 4.1.1 on 2022-09-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ['-created_date'], 'verbose_name': 'Пользователи и заявки', 'verbose_name_plural': 'Пользователи и заявки'},
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='settings',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_anketa_data',
            field=models.CharField(default=None, max_length=4096, verbose_name='Текст заявки'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_anketa_status',
            field=models.CharField(choices=[("('SOLVED', 'Решено')", 'Solved'), ("('ACTIVE', 'Активно')", 'Active'), ("('IN_PROCESS', 'В процессе')", 'In Process'), ("('REJECTED', 'Отклонено')", 'Rejected')], default="('ACTIVE', 'Активно')", max_length=50, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('Частное', 'Private'), ('Юр. лицо', 'Legal Entity')], default='Частное', max_length=50, verbose_name='Тип заявки'),
        ),
    ]
