# Generated by Django 4.1.1 on 2022-09-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0002_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_anketa_list',
            field=models.ManyToManyField(to='Anketa.useranketa'),
        ),
        migrations.AddField(
            model_name='useranketa',
            name='data',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_anketa_status',
            field=models.CharField(choices=[('SOLVED', 'Решено'), ('ACTIVE', 'Активно'), ('IN_PROCESS', 'В процессе'), ('REJECTED', 'Отклонено')], default='ACTIVE', max_length=50, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('PRIVATE', 'Частное'), ('LEGAL_ENTITY', 'Юр. лицо')], default='PRIVATE', max_length=50, verbose_name='Тип заявки'),
        ),
    ]
