# Generated by Django 4.1.1 on 2022-10-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0003_useraccount_user_anketa_list_useranketa_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnketa2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=255)),
                ('data2', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
