# Generated by Django 4.1 on 2022-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
