# Generated by Django 4.1 on 2022-10-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='accept_terms',
            field=models.BooleanField(default=False, verbose_name='Согласен с правилами'),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to='form_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to='form_imgs/'),
        ),
    ]
